#!/usr/bin/env python3
"""
================================================================================
VERIFY -- what verifies a block in this construct, and what cannot
================================================================================

THE QUESTION

  If the block is the mirror pair, the chaining is causality and the hash is
  time: what is verified, and by whom? Either reality verifies itself at
  every tick, or phi (the fixed point) is the validator every block must
  match against.

Both options are testable, so both are tested, against forgeries.

THREE CANDIDATE VERIFIERS

  LOCAL   check x_(n+1) = 1 + 1/x_n                      needs no constant
  PHI     check |x_n - phi| is decreasing                needs phi
  DELTA   check the invariant Delta = tr^2 - 4det        needs the matrix

FOUR FORGERIES

  A  jump straight to the fixed point
  B  a perfectly valid chain from a different seed
  C  a valid chain under a DIFFERENT law with the same Delta
  D  blocks reordered

WHAT IS ALSO CHECKED

  Whether this construct has a hash at all. A Mobius map is a bijection and
  its inverse costs the same as the forward map, so there is no one-way
  direction to commit to. That is not a detail: it is why there is no miner.

Run:  python3 verify.py
================================================================================
"""

import mpmath as mp

mp.mp.dps = 40
PHI = (1 + mp.sqrt(5)) / 2


def f(x):
    return 1 + 1 / x


def finv(y):
    """The inverse. Note it is exactly as cheap as f."""
    return 1 / (y - 1)


# ============================================================== verifiers

TOL = mp.mpf(10) ** -25


def v_local(chain):
    """Does every consecutive pair satisfy the law?"""
    for a, b in zip(chain, chain[1:]):
        if abs(b - f(a)) > TOL:
            return False
    return True


def v_phi(chain):
    """Is the distance to the fixed point non-increasing?"""
    d = [abs(x - PHI) for x in chain]
    for a, b in zip(d, d[1:]):
        if b > a + TOL:
            return False
    return True


def v_delta(a, b, c, d):
    """Delta of the matrix the chain was generated by."""
    return (a + d) ** 2 - 4 * (a * d - b * c)


# ================================================================ chains

def gen(x0, n=20, law=(1, 1, 1, 0)):
    a, b, c, d = law
    out = [mp.mpf(x0)]
    for _ in range(n):
        x = out[-1]
        out.append((a * x + b) / (c * x + d))
    return out


def main():
    print("=" * 78)
    print("0. THE HONEST CHAIN")
    print("=" * 78)
    print()
    real = gen(1, 20)
    print(f"  law x -> 1 + 1/x,  seed 1,  Delta = {v_delta(1,1,1,0)}")
    print(f"  first six: {[mp.nstr(v, 8) for v in real[:6]]}")
    print(f"  LOCAL {v_local(real)}   PHI {v_phi(real)}")
    print()

    print("=" * 78)
    print("1. FOUR FORGERIES AGAINST THREE VERIFIERS")
    print("=" * 78)
    print()

    # A: jump to the fixed point
    fA = real[:5] + [PHI] * 6
    # B: valid chain, different seed
    fB = gen(7, 20)
    # C: M squared. M = [[1,1],[1,0]] has tr 1, det -1, Delta 5.
    #    M^2 = [[2,1],[1,1]] has tr 3, det 1, Delta = 9 - 4 = 5.
    #    SAME Delta, SAME fixed point phi, and NOT conjugate to M.
    #    The orbit it generates is the honest chain with every second
    #    block dropped, i.e. a chain that ran at half the tick rate.
    lawC = (2, 1, 1, 1)
    fC = gen(1, 20, lawC)
    # D: reordered
    fD = real[:]
    fD[7], fD[12] = fD[12], fD[7]

    print(f"  {'chain':>34} {'LOCAL':>7} {'PHI':>7} {'Delta':>8}")
    print("  " + "-" * 60)
    rows = [
        ("honest", real, v_delta(1, 1, 1, 0)),
        ("A  jump to the fixed point", fA, v_delta(1, 1, 1, 0)),
        ("B  valid chain, seed 7", fB, v_delta(1, 1, 1, 0)),
        ("C  M squared, same Delta", fC, v_delta(*lawC)),
        ("D  two blocks swapped", fD, v_delta(1, 1, 1, 0)),
    ]
    for nm, ch, D in rows:
        print(f"  {nm:>34} {str(v_local(ch)):>7} {str(v_phi(ch)):>7} "
              f"{str(D):>8}")
    print()
    print("  READ THE TABLE.")
    print()
    print("  forgery A passes the PHI check and fails LOCAL. sitting AT the")
    print("  fixed point is the most phi-compliant state there is, and it")
    print("  is a lie about history. so phi cannot be the validator: the")
    print("  state that satisfies it perfectly is the forged one.")
    print()
    print("  forgery B passes BOTH. a valid chain from another seed is")
    print("  indistinguishable by any local or fixed-point test. nothing")
    print("  in the construct pins WHICH history you are on.")
    print()
    print("  forgery C is the honest chain with every second block")
    print("  dropped. same Delta (5), same fixed point, not conjugate to")
    print("  the original. so Delta cannot detect a chain that ran at half")
    print("  the tick rate. it fixes the class and never the member, and it")
    print("  says nothing at all about rate.")
    print()
    print("  forgery D fails LOCAL. ordering IS checkable, pairwise.")
    print()

    print("=" * 78)
    print("2. DOES THE WALKER EVER NEED PHI?")
    print("=" * 78)
    print()
    err = [abs(a - b) for a, b in zip(real, real[1:])]
    print(f"  {'hop':>5} {'err':>22} {'err ratio':>16} {'-log ratio':>14}")
    print("  " + "-" * 60)
    for i in range(1, 8):
        r = err[i] / err[i - 1]
        print(f"  {i:>5} {mp.nstr(err[i], 12):>22} {mp.nstr(r, 12):>16} "
              f"{mp.nstr(-mp.log(r), 10):>14}")
    r = err[-1] / err[-2]
    print(f"  {'...':>5} {mp.nstr(err[-1], 6):>22} {mp.nstr(r, 12):>16} "
          f"{mp.nstr(-mp.log(r), 10):>14}")
    print(f"  2 log phi = {mp.nstr(2*mp.log(PHI), 12)}")
    print()
    print("  the walker reconstructs 2 log phi from differences of its own")
    print("  states. phi is not consulted, it is DERIVED. a derived quantity")
    print("  cannot be the external validator -- it is downstream of the")
    print("  very data it would be validating.")
    print()

    print("=" * 78)
    print("3. IS THERE A HASH AT ALL?")
    print("=" * 78)
    print()
    print("  a hash is one-way: cheap forward, infeasible backward. that")
    print("  asymmetry is what lets a block COMMIT to its predecessor.")
    print()
    x = mp.mpf(1)
    fwd = [x]
    for _ in range(12):
        fwd.append(f(fwd[-1]))
    back = [fwd[-1]]
    for _ in range(12):
        back.append(finv(back[-1]))
    back.reverse()
    print(f"  {'step':>6} {'forward':>22} {'recovered by inverse':>24} "
          f"{'error':>12}")
    print("  " + "-" * 68)
    for i in (0, 1, 4, 8, 12):
        print(f"  {i:>6} {mp.nstr(fwd[i], 14):>22} "
              f"{mp.nstr(back[i], 14):>24} "
              f"{mp.nstr(abs(fwd[i]-back[i]), 4):>12}")
    print()
    print("  the inverse recovers every earlier block exactly, at the same")
    print("  cost as the forward step. f(x) = 1 + 1/x, f^-1(y) = 1/(y-1).")
    print("  one division each.")
    print()
    print("  SO: THERE IS NO HASH. a Mobius map is a bijection on the")
    print("  Riemann sphere and its inverse is another Mobius map. nothing")
    print("  in the dynamics is one-way, so no block can commit to")
    print("  anything, so there is nothing for a miner to do. the absence")
    print("  of an external verifier is not a mystery about the universe.")
    print("  it is a consequence of the map being invertible.")
    print()

    print("=" * 78)
    print("4. WHERE THE ONE-WAYNESS ACTUALLY LIVES")
    print("=" * 78)
    print()
    print("  measured in mirror_fs.py:")
    print()
    print("    readlink(p)                 1 inode")
    print("    which names point at p      full scan,  30,760x")
    print()
    print("  THAT is the asymmetry a chain needs, and it is not in the")
    print("  dynamics. it is in REFERENCE. the forward direction of a")
    print("  reference is cheap; the reverse has nowhere to be stored.")
    print()
    print("  so the construct splits cleanly in two, and the split answers")
    print("  the question:")
    print()
    print("    the LAW  (Mobius) is reversible, has an invariant, and needs")
    print("             no verifier. nothing can be forged about it because")
    print("             nothing is committed.")
    print()
    print("    REFERENCE is irreversible in cost, and that is the only")
    print("             place a commitment could live.")
    print()

    print("=" * 78)
    print("5. THE ANSWER")
    print("=" * 78)
    print()
    print("  neither option in the question survives.")
    print()
    print("  not phi: forgery A shows the fixed point is the state that")
    print("  satisfies a phi-check perfectly while lying about history. and")
    print("  section 2 shows phi is derived from the data, not prior to it.")
    print("  a fixed point is also the one place where the relation carries")
    print("  no information at all, since x_(n+1) = x_n there. the least")
    print("  informative state cannot be the validator.")
    print()
    print("  not self-verification either, in the sense the question means.")
    print("  nothing checks a tick against itself. LOCAL checks a tick")
    print("  against its NEIGHBOUR. what verifies is the PAIR, and what it")
    print("  verifies is the RELATION, not any value.")
    print()
    print("  and the verification is partial, which is the honest part:")
    print("  forgery B passes everything. a valid chain from a different")
    print("  seed is undetectable. so the construct can verify that a")
    print("  transition is LAWFUL and cannot verify that a history is")
    print("  THIS one. Delta names the conjugacy class, never the member.")
    print()
    print("  that gap is the missing unit again, in its fourth costume:")
    print("  Delta is a ratio-like invariant, it fixes the class, and")
    print("  nothing inside the structure picks out which member you are.")


if __name__ == "__main__":
    main()
